export const questionList = [
    {
    question: 'Around the world, around the world...', 
    answer: 'Around the world, around the world',
    artist: 'Daft Punk',
    song: 'Around the World',
    difficulty: 'easy',
    },
    {
    question: `So why can't you see...`, 
    answer: 'You belong with meeeeeeeee, you belong with me',
    artist: 'Taylor Swift',
    song: 'You Belong With Me',
    difficulty: 'easy',
    },
    {
    question: 'Honesty, is such a lonely word...', 
    answer: 'Everyone is so untrueeeee',
    artist: 'Billy Joel',
    song: 'Honesty',
    difficulty: 'medium',
    },
    {
    question: 'Op, op, op op op', 
    answer: 'Oppa gangnam style',
    artist: 'PSY',
    song: 'Gangnam Style',
    difficulty: 'easy',
    },
    {
    question: 'How much better, can I show my love to you...', 
    answer: `Than say "I do, I do, I do"...`,
    artist: 'Drake',
    song: `Yebba's Heartbreak`,
    difficulty: 'medium',
    },
    {
    question: 'I know that diamonds mean money for this art...',
    answer: 'But that`s not the shape of my heart',
    artist: 'Sting',
    song: 'Shape of my Heart',
    difficulty: 'medium',
    },
    { 
    question: `Said you'd let me drive your car, as long as I'm with you...`, 
    answer: `Then we'd wait 'till we get far, and tell me that you'll be gone soon`,
    artist: 'beabadoobee',
    song: 'Ripples',
    difficulty: 'hard',
    },
    {
    question: `I'll be the roundabout...`, 
    answer: `The words will make you out 'n' out`,
    artist: 'Yes',
    song: 'Roundabout',
    difficulty: 'hard',
    },
];